/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package discordstudyquery;

import discordstudyquery.database.DatabaseManager;
import discordstudyquery.database.DemoApplication;
import discordstudyquery.discord.Client;

public class App {
    public static void main(String[] args) throws Exception {
        // DatabaseManager databaseManager = new DatabaseManager();
        // DemoApplication demoApplication = new DemoApplication(databaseManager);
        // demoApplication.run();
        Client client = new Client();
        client.init();
    }
}
